services:
  - type: web
    name: frontseat-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: GOOGLE_CLOUD_PROJECT_ID
        value: frontseat-admin
      - key: GOOGLE_APPLICATION_CREDENTIALS
        fromFile: ./frontseat-service-account.json
